# original headers for output.csv file (from RePORTER downloaded csv files)

ACTIVITY = 'ACTIVITY'
ADMINISTERING_IC = 'ADMINISTERING_IC'
APPLICATION_ID = 'APPLICATION_ID'
APPLICATION_TYPE = 'APPLICATION_TYPE'
ARRA_FUNDED = 'ARRA_FUNDED'
AWARD_NOTICE_DATE = 'AWARD_NOTICE_DATE'
BUDGET_END = 'BUDGET_END'
BUDGET_START = 'BUDGET_START'
CFDA_CODE = 'CFDA_CODE'
CORE_PROJECT_NUM = 'CORE_PROJECT_NUM'
DIRECT_COST_AMT = 'DIRECT_COST_AMT'
ED_INST_TYPE = 'ED_INST_TYPE'
FOA_NUMBER = 'FOA_NUMBER'
FULL_PROJECT_NUM = 'FULL_PROJECT_NUM'
FUNDING_ICS = 'FUNDING_ICS'
FUNDING_MECHANISM = 'FUNDING_MECHANISM'
FY = 'FY'
IC_NAME = 'IC_NAME'
INDIRECT_COST_AMT = 'INDIRECT_COST_AMT'
NIH_SPENDING_CATS = 'NIH_SPENDING_CATS'
ORG_CITY = 'ORG_CITY'
ORG_COUNTRY = 'ORG_COUNTRY'
ORG_DEPT = 'ORG_DEPT'
ORG_DISTRICT = 'ORG_DISTRICT'
ORG_DUNS = 'ORG_DUNS'
ORG_FIPS = 'ORG_FIPS'
ORG_IPF_CODE = 'ORG_IPF_CODE'
ORG_NAME = 'ORG_NAME'
ORG_STATE = 'ORG_STATE'
ORG_ZIPCODE = 'ORG_ZIPCODE'
PHR ='PHR'
PI_IDS = 'PI_IDS'
PI_NAMES = 'PI_NAMES'
PROGRAM_OFFICER_NAME = 'PROGRAM_OFFICER_NAME'
PROJECT_END = 'PROJECT_END'
PROJECT_START = 'PROJECT_START'
PROJECT_TERMS = 'PROJECT_TERMS'
PROJECT_TITLE = 'PROJECT_TITLE'
SERIAL_NUMBER = 'SERIAL_NUMBER'
STUDY_SECTION = 'STUDY_SECTION'
STUDY_SECTION_NAME = 'STUDY_SECTION_NAME'
SUBPROJECT_ID = 'SUBPROJECT_ID'
SUFFIX = 'SUFFIX'
SUPPORT_YEAR = 'SUPPORT_YEAR'
TOTAL_COST = 'TOTAL_COST'
TOTAL_COST_SUB_PROJECT = 'TOTAL_COST_SUB_PROJECT'


# new headers for enhanced-output.csv file (added for the project)

NB_PI_IDS = 'NB_PI_IDS'
NB_PI_NAMES = 'NB_PI_NAMES'
CONTACT_PI_ID = 'CONTACT_PI_ID'
CONTACT_PI_NAME = 'CONTACT_PI_NAME'
CONTACT_PI_ID_STATUS = 'CONTACT_PI_ID_STATUS'
CONTACT_PI_NAME_STATUS = 'CONTACT_PI_NAME_STATUS'
CONTACT_PI_FIRST_NAME = 'CONTACT_PI_FIRST_NAME'
CONTACT_PI_GENDER = 'CONTACT_PI_GENDER'



# original headers for output.csv file (from RePORTER downloaded csv files)

ORDERED_HEADERS = [
    APPLICATION_ID,
    ACTIVITY,
    ADMINISTERING_IC,
    APPLICATION_TYPE,
    ARRA_FUNDED,
    AWARD_NOTICE_DATE,
    BUDGET_START,
    BUDGET_END,
    CFDA_CODE,
    CORE_PROJECT_NUM,
    ED_INST_TYPE,
    FOA_NUMBER,
    FULL_PROJECT_NUM,
    FUNDING_ICS,
    FUNDING_MECHANISM,
    FY,
    IC_NAME,
    NIH_SPENDING_CATS,
    ORG_CITY,
    ORG_COUNTRY,
    ORG_DEPT,
    ORG_DISTRICT,
    ORG_DUNS,
    ORG_FIPS,
    ORG_IPF_CODE,
    ORG_NAME,
    ORG_STATE,
    ORG_ZIPCODE,
    PHR,
    PI_IDS,
    PI_NAMES,
    PROGRAM_OFFICER_NAME,
    PROJECT_START,
    PROJECT_END,
    PROJECT_TERMS,
    PROJECT_TITLE,
    SERIAL_NUMBER,
    STUDY_SECTION,
    STUDY_SECTION_NAME,
    SUBPROJECT_ID,
    SUFFIX,
    SUPPORT_YEAR,
    DIRECT_COST_AMT,
    INDIRECT_COST_AMT,
    TOTAL_COST,
    TOTAL_COST_SUB_PROJECT
                 ]